### PR TITLE
remove break line causing escape problems

### PR DESCRIPTION
**Pull request by lucasmellos**
related to https://github.com/signalwire/conference-manager/actions/runs/4861751967/jobs/8672972796 
image

@ryanwi FYI 👆🏻

### CODE REVIEW

**Comment by Null-Is-Null** [comment]
Instead of removing the newlines, would escaping them make the final payload valid JSON?

**Comment by ryanwi** [comment]
FS has https://github.com/signalwire/signalwire-freeswitch/blob/master/.github/workflows/build.yml#L1139

**Comment by ryanwi** [comment]
(and it's working)

**Comment by Null-Is-Null** [comment]
Ah, now that's interesting. The line from the GS workflow doesn't have single quotes around the `MESSAGE` input value, but the workflow for this repo does. Maybe we just need to remove the quotes instead?

**Comment by ryanwi** [comment]
There's also no space after the `\n` 's in the FS one. maybe that's part of it too?

**Comment by ryanwi** [comment]
it also has the trailing `>` so each is `\n>`

**Comment by Null-Is-Null** [comment]
I think the `>` is markup so that Slack formats it like a block, similar to this:

image

**Comment by ryanwi** [comment]
> it also has the trailing `>` so each is `\n>`

never mind, yeah `>` is highlight/block

https://api.slack.com/reference/surfaces/formatting#block-formatting

**Comment by ryanwi** [comment]
so, maybe just avoid the space after `\n`

This isn't too clear, but there is no space after `\n` in the example

https://api.slack.com/reference/surfaces/formatting#line-breaks

**Comment by ryanwi** [comment]
(or just use the FS example too, so we get the block/highlight too)

**Comment by lucasmellos** [comment]
that looks good @ryanwi I've submitted a new commit

**Review by ryanwi — APPROVED** [review]

**Comment by lucasmellos** [comment]
@ryanwi may you trigger a deployment?

**Comment by ryanwi** [comment]
does a re-run pull it in? (running https://github.com/signalwire/conference-manager/actions/runs/4861751967 , but it is a re-run)

**Comment by lucasmellos** [comment]
Nope

--
Lucas Mellos Carlos

**Comment by ryanwi** [comment]
Can we have it be consistent with the old deploy messages from drone?

instead of "GitHub Action result" something like `Update Service`


drone one: https://signalwire.slack.com/archives/CEHU2TMC0/p1683058438982649

latest gha one: https://signalwire.slack.com/archives/CEHU2TMC0/p1683060673683709

**Comment by ryanwi** [comment]
looks like it went through though

**Comment by lucasmellos** [comment]
Yep np

--
Lucas Mellos Carlos

**Comment by ryanwi** [comment]
Would be good to include the service name too?

The taxman deploy has two slack messages that are identical, guessing it's the matrix of services being deployed?

Screenshot 2023-05-02 at 4 46 03 PM

**Pull request merged**
