### PR TITLE
Add secrets required for OVH provisioning

### PR DESCRIPTION
**Pull request by Null-Is-Null**
Required for https://github.com/signalwire/cloud-product/issues/5260

### CODE REVIEW

**Review by lucasmellos — COMMENTED** [review]
Shouldn't have TF_VAR before the actual variable?

**Comment by Null-Is-Null** [comment]
As long as those secrets are set as environment vars, the terraform providers should be able to use them which has worked in local testing. Does that behavior hold when run as an Action, or is it better practice to set them from vars in the provider config?

**Comment by lucasmellos** [comment]
just looked at the provider and it should work https://registry.terraform.io/providers/ovh/ovh/latest/docs

**Review by lucasmellos — APPROVED** [review]

**Comment by Null-Is-Null** [comment]
For reference, the environment variables used for OpenStack provider configuration (also required for provisioning on OVH) is documented at https://registry.terraform.io/providers/terraform-provider-openstack/openstack/latest/docs#configuration-reference.

**Pull request merged**
